### ISSUE TITLE
Fehler mit ocamlc 4.02.1, 4.02.2 und 4.02.3

### ISSUE THREAD

**Issue by lukas-123** [vogler/info2-ha#3]
Da in batteries.ml String.init verwendet wird, muss man mindestens ocamlc version 4.02.0 verwenden. In dieser Version funktioniert jedoch [merlin](https://github.com/the-lambda-church) nicht.
In den höheren Versionen tritt folgender Fehler auf:
```
ocamlc -o ha5.out batteries.cmo ha5.mli ha5.ml 
File "ha5.mli", line 1:
Error: The files /home/lukas/.opam/4.02.3/lib/ocaml/pervasives.cmi
       and batteries.cmi make inconsistent assumptions
       over interface Pervasives

```

**Comment by vogler** [comment]
Du musst batteries.ml neu kompilieren wenn du den Compiler wechselst.
Ich habe ocaml 4.02.3 und merlin funktioniert.

**Comment by lukas-123** [comment]
Vielen Dank, das hat das Problem behoben.
